import { MigrateUpArgs, MigrateDownArgs, sql } from "@payloadcms/db-postgres";

export async function up({ db }: MigrateUpArgs): Promise<void> {
    await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_hero_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_hero_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_homepage_hero_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_homepage_hero_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_branches_grid_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_branches_grid_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_branch_details_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_branch_details_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_form_block_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_form_block_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_client_service_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_client_service_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_services_grid_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_services_grid_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_metrics_strip_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_metrics_strip_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_products_grid_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_products_grid_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_logo_marquee_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_logo_marquee_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_centered_cta_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_centered_cta_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_process_steps_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_process_steps_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_company_timeline_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_company_timeline_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_service_section_intro_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_service_section_intro_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_split_content_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_split_content_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_flex_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_flex_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_computer_audience_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_computer_audience_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_computer_catalog_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_computer_catalog_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_computer_product_catalog_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_computer_product_catalog_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_media_feature_grid_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_media_feature_grid_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_technology_spotlight_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_technology_spotlight_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_editorial_columns_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum_pages_blocks_editorial_columns_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_hero_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_hero_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_homepage_hero_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_homepage_hero_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_branches_grid_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_branches_grid_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_branch_details_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_branch_details_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_client_service_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_client_service_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_services_grid_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_services_grid_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_metrics_strip_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_metrics_strip_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_products_grid_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_products_grid_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_logo_marquee_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_logo_marquee_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_centered_cta_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_centered_cta_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_process_steps_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_process_steps_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_company_timeline_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_company_timeline_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_service_section_intro_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_service_section_intro_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_split_content_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_split_content_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__flex_v_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__flex_v_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_computer_audience_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_computer_audience_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_computer_catalog_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_computer_catalog_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_computer_product_catalog_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_computer_product_catalog_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_media_feature_grid_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_media_feature_grid_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_technology_spotlight_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_technology_spotlight_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_editorial_columns_spacing_top" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_editorial_columns_spacing_bottom" AS ENUM('auto', 'none', 'compact', 'normal', 'large');
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "spacing_top" "enum_pages_blocks_hero_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "spacing_bottom" "enum_pages_blocks_hero_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_homepage_hero" ADD COLUMN "spacing_top" "enum_pages_blocks_homepage_hero_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_homepage_hero" ADD COLUMN "spacing_bottom" "enum_pages_blocks_homepage_hero_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_branches_grid" ADD COLUMN "spacing_top" "enum_pages_blocks_branches_grid_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_branches_grid" ADD COLUMN "spacing_bottom" "enum_pages_blocks_branches_grid_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_branch_details" ADD COLUMN "spacing_top" "enum_pages_blocks_branch_details_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_branch_details" ADD COLUMN "spacing_bottom" "enum_pages_blocks_branch_details_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "spacing_top" "enum_pages_blocks_form_block_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "spacing_bottom" "enum_pages_blocks_form_block_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_client_service" ADD COLUMN "spacing_top" "enum_pages_blocks_client_service_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_client_service" ADD COLUMN "spacing_bottom" "enum_pages_blocks_client_service_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_services_grid" ADD COLUMN "spacing_top" "enum_pages_blocks_services_grid_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_services_grid" ADD COLUMN "spacing_bottom" "enum_pages_blocks_services_grid_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_metrics_strip" ADD COLUMN "spacing_top" "enum_pages_blocks_metrics_strip_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_metrics_strip" ADD COLUMN "spacing_bottom" "enum_pages_blocks_metrics_strip_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_products_grid" ADD COLUMN "spacing_top" "enum_pages_blocks_products_grid_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_products_grid" ADD COLUMN "spacing_bottom" "enum_pages_blocks_products_grid_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_logo_marquee" ADD COLUMN "spacing_top" "enum_pages_blocks_logo_marquee_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_logo_marquee" ADD COLUMN "spacing_bottom" "enum_pages_blocks_logo_marquee_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_centered_cta" ADD COLUMN "spacing_top" "enum_pages_blocks_centered_cta_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_centered_cta" ADD COLUMN "spacing_bottom" "enum_pages_blocks_centered_cta_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_process_steps" ADD COLUMN "spacing_top" "enum_pages_blocks_process_steps_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_process_steps" ADD COLUMN "spacing_bottom" "enum_pages_blocks_process_steps_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_company_timeline" ADD COLUMN "spacing_top" "enum_pages_blocks_company_timeline_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_company_timeline" ADD COLUMN "spacing_bottom" "enum_pages_blocks_company_timeline_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_service_section_intro" ADD COLUMN "spacing_top" "enum_pages_blocks_service_section_intro_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_service_section_intro" ADD COLUMN "spacing_bottom" "enum_pages_blocks_service_section_intro_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_split_content" ADD COLUMN "spacing_top" "enum_pages_blocks_split_content_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_split_content" ADD COLUMN "spacing_bottom" "enum_pages_blocks_split_content_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "flex" ADD COLUMN "spacing_top" "enum_flex_spacing_top" DEFAULT 'auto';
  ALTER TABLE "flex" ADD COLUMN "spacing_bottom" "enum_flex_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_computer_audience" ADD COLUMN "spacing_top" "enum_pages_blocks_computer_audience_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_computer_audience" ADD COLUMN "spacing_bottom" "enum_pages_blocks_computer_audience_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_computer_catalog" ADD COLUMN "spacing_top" "enum_pages_blocks_computer_catalog_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_computer_catalog" ADD COLUMN "spacing_bottom" "enum_pages_blocks_computer_catalog_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_computer_product_catalog" ADD COLUMN "spacing_top" "enum_pages_blocks_computer_product_catalog_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_computer_product_catalog" ADD COLUMN "spacing_bottom" "enum_pages_blocks_computer_product_catalog_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_media_feature_grid" ADD COLUMN "spacing_top" "enum_pages_blocks_media_feature_grid_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_media_feature_grid" ADD COLUMN "spacing_bottom" "enum_pages_blocks_media_feature_grid_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_technology_spotlight" ADD COLUMN "spacing_top" "enum_pages_blocks_technology_spotlight_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_technology_spotlight" ADD COLUMN "spacing_bottom" "enum_pages_blocks_technology_spotlight_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_editorial_columns" ADD COLUMN "spacing_top" "enum_pages_blocks_editorial_columns_spacing_top" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_editorial_columns" ADD COLUMN "spacing_bottom" "enum_pages_blocks_editorial_columns_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "spacing_top" "enum__pages_v_blocks_hero_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_hero_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_homepage_hero" ADD COLUMN "spacing_top" "enum__pages_v_blocks_homepage_hero_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_homepage_hero" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_homepage_hero_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_branches_grid" ADD COLUMN "spacing_top" "enum__pages_v_blocks_branches_grid_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_branches_grid" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_branches_grid_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_branch_details" ADD COLUMN "spacing_top" "enum__pages_v_blocks_branch_details_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_branch_details" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_branch_details_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "spacing_top" "enum__pages_v_blocks_form_block_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_form_block_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_client_service" ADD COLUMN "spacing_top" "enum__pages_v_blocks_client_service_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_client_service" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_client_service_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_services_grid" ADD COLUMN "spacing_top" "enum__pages_v_blocks_services_grid_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_services_grid" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_services_grid_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_metrics_strip" ADD COLUMN "spacing_top" "enum__pages_v_blocks_metrics_strip_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_metrics_strip" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_metrics_strip_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_products_grid" ADD COLUMN "spacing_top" "enum__pages_v_blocks_products_grid_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_products_grid" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_products_grid_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_logo_marquee" ADD COLUMN "spacing_top" "enum__pages_v_blocks_logo_marquee_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_logo_marquee" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_logo_marquee_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_centered_cta" ADD COLUMN "spacing_top" "enum__pages_v_blocks_centered_cta_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_centered_cta" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_centered_cta_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_process_steps" ADD COLUMN "spacing_top" "enum__pages_v_blocks_process_steps_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_process_steps" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_process_steps_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_company_timeline" ADD COLUMN "spacing_top" "enum__pages_v_blocks_company_timeline_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_company_timeline" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_company_timeline_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_service_section_intro" ADD COLUMN "spacing_top" "enum__pages_v_blocks_service_section_intro_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_service_section_intro" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_service_section_intro_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_split_content" ADD COLUMN "spacing_top" "enum__pages_v_blocks_split_content_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_split_content" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_split_content_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_flex_v" ADD COLUMN "spacing_top" "enum__flex_v_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_flex_v" ADD COLUMN "spacing_bottom" "enum__flex_v_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_computer_audience" ADD COLUMN "spacing_top" "enum__pages_v_blocks_computer_audience_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_computer_audience" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_computer_audience_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_computer_catalog" ADD COLUMN "spacing_top" "enum__pages_v_blocks_computer_catalog_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_computer_catalog" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_computer_catalog_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_computer_product_catalog" ADD COLUMN "spacing_top" "enum__pages_v_blocks_computer_product_catalog_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_computer_product_catalog" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_computer_product_catalog_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_media_feature_grid" ADD COLUMN "spacing_top" "enum__pages_v_blocks_media_feature_grid_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_media_feature_grid" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_media_feature_grid_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_technology_spotlight" ADD COLUMN "spacing_top" "enum__pages_v_blocks_technology_spotlight_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_technology_spotlight" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_technology_spotlight_spacing_bottom" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_editorial_columns" ADD COLUMN "spacing_top" "enum__pages_v_blocks_editorial_columns_spacing_top" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_editorial_columns" ADD COLUMN "spacing_bottom" "enum__pages_v_blocks_editorial_columns_spacing_bottom" DEFAULT 'auto';`);
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
    await db.execute(sql`
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_homepage_hero" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_homepage_hero" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_branches_grid" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_branches_grid" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_branch_details" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_branch_details" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_client_service" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_client_service" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_services_grid" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_services_grid" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_metrics_strip" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_metrics_strip" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_products_grid" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_products_grid" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_logo_marquee" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_logo_marquee" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_centered_cta" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_centered_cta" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_process_steps" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_process_steps" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_company_timeline" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_company_timeline" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_service_section_intro" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_service_section_intro" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_split_content" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_split_content" DROP COLUMN "spacing_bottom";
  ALTER TABLE "flex" DROP COLUMN "spacing_top";
  ALTER TABLE "flex" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_computer_audience" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_computer_audience" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_computer_catalog" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_computer_catalog" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_computer_product_catalog" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_computer_product_catalog" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_media_feature_grid" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_media_feature_grid" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_technology_spotlight" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_technology_spotlight" DROP COLUMN "spacing_bottom";
  ALTER TABLE "pages_blocks_editorial_columns" DROP COLUMN "spacing_top";
  ALTER TABLE "pages_blocks_editorial_columns" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_homepage_hero" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_homepage_hero" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_branches_grid" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_branches_grid" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_branch_details" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_branch_details" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_client_service" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_client_service" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_services_grid" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_services_grid" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_metrics_strip" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_metrics_strip" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_products_grid" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_products_grid" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_logo_marquee" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_logo_marquee" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_centered_cta" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_centered_cta" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_process_steps" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_process_steps" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_company_timeline" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_company_timeline" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_service_section_intro" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_service_section_intro" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_split_content" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_split_content" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_flex_v" DROP COLUMN "spacing_top";
  ALTER TABLE "_flex_v" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_computer_audience" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_computer_audience" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_computer_catalog" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_computer_catalog" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_computer_product_catalog" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_computer_product_catalog" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_media_feature_grid" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_media_feature_grid" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_technology_spotlight" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_technology_spotlight" DROP COLUMN "spacing_bottom";
  ALTER TABLE "_pages_v_blocks_editorial_columns" DROP COLUMN "spacing_top";
  ALTER TABLE "_pages_v_blocks_editorial_columns" DROP COLUMN "spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_hero_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_hero_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_homepage_hero_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_homepage_hero_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_branches_grid_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_branches_grid_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_branch_details_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_branch_details_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_form_block_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_form_block_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_client_service_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_client_service_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_services_grid_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_services_grid_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_metrics_strip_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_metrics_strip_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_products_grid_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_products_grid_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_logo_marquee_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_logo_marquee_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_centered_cta_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_centered_cta_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_process_steps_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_process_steps_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_company_timeline_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_company_timeline_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_service_section_intro_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_service_section_intro_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_split_content_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_split_content_spacing_bottom";
  DROP TYPE "public"."enum_flex_spacing_top";
  DROP TYPE "public"."enum_flex_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_computer_audience_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_computer_audience_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_computer_catalog_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_computer_catalog_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_computer_product_catalog_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_computer_product_catalog_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_media_feature_grid_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_media_feature_grid_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_technology_spotlight_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_technology_spotlight_spacing_bottom";
  DROP TYPE "public"."enum_pages_blocks_editorial_columns_spacing_top";
  DROP TYPE "public"."enum_pages_blocks_editorial_columns_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_hero_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_hero_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_homepage_hero_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_homepage_hero_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_branches_grid_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_branches_grid_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_branch_details_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_branch_details_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_client_service_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_client_service_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_services_grid_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_services_grid_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_metrics_strip_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_metrics_strip_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_products_grid_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_products_grid_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_logo_marquee_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_logo_marquee_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_centered_cta_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_centered_cta_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_process_steps_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_process_steps_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_company_timeline_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_company_timeline_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_service_section_intro_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_service_section_intro_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_split_content_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_split_content_spacing_bottom";
  DROP TYPE "public"."enum__flex_v_spacing_top";
  DROP TYPE "public"."enum__flex_v_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_computer_audience_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_computer_audience_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_computer_catalog_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_computer_catalog_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_computer_product_catalog_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_computer_product_catalog_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_media_feature_grid_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_media_feature_grid_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_technology_spotlight_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_technology_spotlight_spacing_bottom";
  DROP TYPE "public"."enum__pages_v_blocks_editorial_columns_spacing_top";
  DROP TYPE "public"."enum__pages_v_blocks_editorial_columns_spacing_bottom";`);
}
